version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/php:7.3.11
    steps:
      - checkout
      - run:
          name: Creating known_hosts file
          command: mkdir -p ~/.ssh && touch ~/.ssh/known_hosts
      - run:
          name: Adding Heroku to known hosts
          command: ssh-keyscan -H heroku.com >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "7b:c2:bf:16:79:f9:8a:67:ec:e7:16:01:b8:6e:d5:69"
      - deploy:
          command: git push -f git@heroku.com:cci-81277.git $CIRCLE_SHA1:master
workflows:
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - deploy
