version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/node:12.15-browsers
    steps:
      - checkout
      - git push -f git@heroku.com:cci-81277.git $CIRCLE_SHA1:master
workflows:
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - deploy
