version: 2.1
orbs:
  heroku: circleci/heroku@1.2.3

jobs:
  deploy:
    docker:
      - image: circleci/php:7.3.11
    steps:
      - run:
          name: SSH Key
          command: git config --global url.ssh://git@heroku.com/.insteadOf https://git.heroku.com/
      - checkout
      - heroku/deploy-via-git
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - deploy
