version: 2.1
orbs:
  heroku: circleci/heroku@1.2.3

jobs:
  deploy:
    docker:
      - image: circleci/php:7.3.11
    steps:
      - checkout
      - heroku/deploy-via-git
workflows:
  # Name the workflow "welcome"
  welcome:
    jobs:
      - deploy
